- src/components/Accordion/Accordion.jsx
- src/components/Accordion/Accordion.spec.js
- src/components/Accordion/AccordionItem/AccordionItem.jsx
- src/components/Button/Button.jsx
- src/components/Button/Button.spec.js
- src/components/PrimaryNav/PrimaryNav.jsx
- src/components/PrimaryNav/PrimaryNav.spec.js
- src/components/PrimaryNav/PrimaryNavItem/PrimaryNavItem.jsx
- src/components/PrimaryNav/PrimaryNavItem/PrimaryNavItem.spec.js
- src/components/PrimaryNav/PrimaryNavItemsGroup/PrimaryNavItemsGroup.jsx
- src/components/PrimaryNav/PrimaryNavItemsGroup/PrimaryNavItemsGroup.spec.js
- src/components/ResizableBox/Resizable.spec.js
- src/components/ResizableBox/ResizableBox.jsx
- src/components/SecondaryNav/SecondaryNav.jsx
- src/components/SecondaryNav/SecondaryNav.spec.js
- src/components/Separator/Separator.jsx
- src/components/Separator/Separator.spec.js
- src/components/TreeView/ControlledTreeView.jsx
- src/components/TreeView/TreeView.spec.js
- src/components/Typography/Typography.spec.js
https://jira.jahia.org/browse/MOON-56
Allow all components to add custom attributes
> MOON-56: Allow all components to add custom attributes

- src/components/Accordion/Accordion.jsx
- src/components/Accordion/AccordionItem/AccordionItem.jsx
- src/components/Button/Button.jsx
- src/components/GlobalStyle/GlobalStyle.jsx
- src/components/PrimaryNav/PrimaryNav.jsx
- src/components/PrimaryNav/PrimaryNavItem/PrimaryNavItem.jsx
- src/components/PrimaryNav/PrimaryNavItemsGroup/PrimaryNavItemsGroup.jsx
- src/components/ResizableBox/ResizableBox.jsx
- src/components/SecondaryNav/SecondaryNav.jsx
- src/components/Separator/Separator.jsx
- src/components/TreeView/TreeView.jsx
- src/components/Typography/Typography.jsx
- src/layouts/app/LayoutApp.jsx
- src/layouts/module/LayoutModule.jsx
https://jira.jahia.org/browse/MOON-60
Add a displayName for each components
> MOON-60: Add a displayName

- README.md
- src/tokens/colors/_colors.scss
https://jira.jahia.org/browse/MOON-62
update colors
> MOON-62 update colors

- src/tokens/colors/_colors.scss
https://jira.jahia.org/browse/MOON-62
fix issue with basic colors
> MOON-62 fix issue with basic colors

- .github/workflows/deploy-storybook.yml
- README.md
https://jira.jahia.org/browse/MOON-30
Deploy storybook to github pages when moonstone is released
> MOON-30: Add github workflow to deploy storybook on github pages

- src/components/Accordion/Accordion.stories.jsx
- src/components/Accordion/AccordionItem/AccordionItem.stories.jsx
- src/components/PrimaryNav/PrimaryNav.jsx
- src/components/PrimaryNav/PrimaryNav.stories.jsx
- src/components/PrimaryNav/PrimaryNavItem/PrimaryNavItem.stories.jsx
- src/components/PrimaryNav/PrimaryNavItemsGroup/PrimaryNavItemsGroup.stories.jsx
- src/components/ResizableBox/ResizableBox.jsx
- src/components/SecondaryNav/SecondaryNav.jsx
- src/components/SecondaryNav/SecondaryNav.stories.jsx
- src/components/TreeView/ControlledTreeView.jsx
- src/components/TreeView/TreeView.stories.jsx
- src/tokens/icons/Icons.md
- src/tokens/icons/_icons.scss
https://jira.jahia.org/browse/MOON-51
Update icon API
> MOON-51 update icon api

- src/components/TreeView/ControlledTreeView.jsx
- src/components/TreeView/TreeView.jsx
- src/components/TreeView/TreeView.md
- src/components/TreeView/TreeView.scss
- src/components/TreeView/TreeView.spec.js
- src/components/TreeView/TreeView.stories.jsx
- src/components/TreeView/UncontrolledTreeView.jsx
> MOON-67 : Fixed styling, handle root node

- src/components/Accordion/AccordionItem/AccordionItem.jsx
- src/components/PrimaryNav/PrimaryNav.stories.jsx
- src/components/PrimaryNav/PrimaryNavItem/PrimaryNavItem.jsx
> MOON-51 : Fixed icon size in PrimaryNavItem

- src/__storybook__/storybook.scss
- src/components/Chip/Chip.jsx
- src/components/Chip/Chip.scss
- src/components/Chip/Chip.spec.js
- src/components/Chip/Chip.stories.jsx
https://jira.jahia.org/browse/MOON-50
* enforce icon size to always be small
* fix spacing between label and icon
* improved stories book
> MOON-50: Enforce icon size in Chip component

- src/__storybook__/storybook.scss
- src/components/Chip/Chip.jsx
- src/components/Chip/Chip.scss
- src/components/Chip/Chip.spec.js
- src/components/Chip/Chip.stories.jsx
https://jira.jahia.org/browse/MOON-50
Added a isDisabled property to disable a chip
see https://www.figma.com/file/939bW74C3TLW5VAzK23uox/moonstone-components?node-id=1084%3A1222
> MOON-50: Add isDisabled property to Chip component

- CONTRIBUTING.md
> Updated css guidelines

- src/__storybook__/IconWrapper.jsx
- src/__storybook__/utils.js
- src/components/Button/Button.jsx
- src/components/Button/Button.scss
- src/components/Button/Button.spec.js
- src/components/Button/Button.stories.jsx
- src/components/Button/variants/_default.scss
- src/components/Button/variants/_ghost.scss
- src/components/Button/variants/_outlined.scss
- src/tokens/colors/_colors.scss
https://jira.jahia.org/browse/MOON-51
- implement buttons
- update API and sass
- implement storybook
- implement test
- make all icons available in all tests
> MOON-51 implement buttons, update API and sass, implement storybook, implement test, make all icons available in all tests

- src/components/Dropdown/Dropdown.stories.jsx
> MOON-12: fixed onchange in storybook

- src/components/Badge/Badge.jsx
- src/components/Badge/Badge.md
- src/components/Badge/Badge.scss
- src/components/Badge/Badge.spec.js
- src/components/Badge/Badge.stories.jsx
- src/components/Badge/index.js
- src/components/PrimaryNav/PrimaryNav.stories.jsx
- src/components/PrimaryNav/PrimaryNavItem/PrimaryNavItem.jsx
- src/components/PrimaryNav/PrimaryNavItem/PrimaryNavItem.scss
- src/components/index.js
- src/layouts/Layouts.stories.jsx
https://jira.jahia.org/browse/MOON-68
Added badge component needed for worklow. I added three sizes, several color options and two variants (round and diamond).
> Moon 68 Badge component

- src/components/Button/Button.scss
- src/components/Button/variants/_ghost.scss
https://jira.jahia.org/browse/MOON-72
- Remove default outline for each button variants
- Add cursor `pointer` when the button isn't disabled
- Add cursor `not-allowed` when the button is disabled
- Add a transparent border for the ghost button to avoid a "jump" on hovering
- Fix an issue with ghost danger button
> MOON-72: UI/UX button improvement

- src/components/Badge/Badge.jsx
- src/components/Badge/Badge.scss
- src/components/Badge/Badge.spec.js
- src/components/Badge/Badge.stories.jsx
- src/components/Chip/Chip.jsx
- src/components/PrimaryNav/PrimaryNav.stories.jsx
- src/components/PrimaryNav/PrimaryNavItem/PrimaryNavItem.jsx
- src/components/PrimaryNav/PrimaryNavItem/PrimaryNavItem.scss
- src/components/PrimaryNav/PrimaryNavItem/PrimaryNavItem.stories.jsx
- src/components/PrimaryNav/PrimaryNavItemsGroup/PrimaryNavItemsGroup.stories.jsx
https://jira.jahia.org/browse/MOON-70
- Update badge design
- Remove the size props
- Add tests
> Moon 70: Update Badge design

- src/components/Button/Button.jsx
- src/components/Button/variants/_default.scss
- src/components/Button/variants/_ghost.scss
- src/components/Button/variants/_outlined.scss
- src/components/Typography/Typography.scss
- src/tokens/colors/_colors.scss
https://jira.jahia.org/browse/MOON-51
update button css to reflect latest changes, also remove warning and success color from the API and from the css, as they have been removed from figma.
> MOON-51 update button css to reflect latest changes

- package.json
- src/components/Dropdown/Dropdown.jsx
- src/components/Dropdown/Dropdown.scss
- src/components/Dropdown/Dropdown.spec.js
- src/components/ListItem/ListItem.jsx
- src/components/ListItem/ListItem.spec.js
- src/components/Menu/Menu.jsx
- src/components/Menu/Menu.scss
- src/components/Menu/Menu.spec.js
- src/components/Menu/Menu.stories.jsx
- src/components/Menu/MenuItem.jsx
- src/components/Menu/MenuItem.scss
- src/components/Menu/index.js
- src/tokens/spacings/_spacings.scss
- yarn.lock
https://jira.jahia.org/browse/MOON-36
> MOON-36 : Menu positioning

- src/components/Separator/Separator.jsx
- src/components/Separator/Separator.scss
- src/components/Separator/Separator.spec.js
- src/components/Separator/Separator.stories.jsx
https://jira.jahia.org/browse/MOON-73
Add vertical variant to the Separator component
> MOON-73: Add vertical variant to the Separator component

- .npmignore
- src/components/Dropdown/Dropdown.scss
> MOON-12 : Fixed styling

- src/components/Menu/Menu.jsx
- src/components/Menu/Menu.stories.jsx
- src/hooks/useEnterExitCallbacks.jsx
- src/hooks/usePositioning.jsx
> MOON-36 : split code with custom hooks

- src/components/Accordion/AccordionItem/AccordionItem.jsx
- src/components/PrimaryNav/PrimaryNav.jsx
- src/components/PrimaryNav/PrimaryNav.spec.js
- src/components/ResizableBox/ResizableBox.jsx
https://jira.jahia.org/browse/BACKLOG-12479
Add role attribute to improve selectability of items for QA
> BACKLOG-12479 Add roles to resizable and accordion item

- src/components/Typography/Typography.jsx
> Fix warning issue when using mixed prod/dev

- src/components/ButtonGroup/ButtonGroup.jsx
- src/components/ButtonGroup/ButtonGroup.md
- src/components/ButtonGroup/ButtonGroup.scss
- src/components/ButtonGroup/ButtonGroup.spec.js
- src/components/ButtonGroup/ButtonGroup.stories.jsx
- src/components/ButtonGroup/index.js
https://jira.jahia.org/browse/MOON-61
Create ButtonGroup component
> MOON-61: Create ButtonGroup component

- src/components/PrimaryNav/PrimaryNavItem/PrimaryNavItem.scss
- src/components/PrimaryNav/PrimaryNavItem/PrimaryNavItem.stories.jsx
https://jira.jahia.org/browse/MOON-78
Fix PrimaryNavItem button when it's selected
> MOON-78: Fix PrimaryNavItem button when it's selected

- src/components/Dropdown/Dropdown.jsx
- src/components/Dropdown/Dropdown.stories.jsx
- src/components/Menu/Menu.jsx
- src/components/Menu/Menu.stories.jsx
https://jira.jahia.org/browse/MOON-79
- The Menu should be scrollable
- Add a maxHeight to the Dropdown's menu
> MOON-79: Menu should be scrollable

- src/components/index.js
> MOON-61  : Export component

- src/components/PrimaryNav/PrimaryNavItem/PrimaryNavItem.scss
https://jira.jahia.org/browse/MOON-83
Fix PrimaryNav's icon alignment
> MOON-83: Fix PrimaryNav's icon alignment

- src/globals/_layout.scss
https://jira.jahia.org/browse/MOON-88
- Add `min-width: 0` and `min-height: 0` to `.flexFluid`
> MOON-88: Fix flex layout

- src/__storybook__/storybook.scss
- src/components/Breadcrumb/Breadcrumb.jsx
- src/components/Breadcrumb/Breadcrumb.md
- src/components/Breadcrumb/Breadcrumb.scss
- src/components/Breadcrumb/Breadcrumb.spec.js
- src/components/Breadcrumb/Breadcrumb.stories.jsx
- src/components/Breadcrumb/BreadcrumbItem/BreadcrumbItem.jsx
- src/components/Breadcrumb/BreadcrumbItem/BreadcrumbItem.scss
- src/components/Breadcrumb/BreadcrumbItem/BreadcrumbItem.spec.js
- src/components/Breadcrumb/BreadcrumbItem/index.js
- src/components/Breadcrumb/index.js
- src/components/Button/Button.jsx
- src/components/index.js
https://jira.jahia.org/browse/MOON-49
- Add the Breadcruumb component
> MOON-49: Add Breadcrumb component

- src/__storybook__/storybook.scss
- src/components/Breadcrumb/Breadcrumb.stories.jsx
- src/components/Breadcrumb/BreadcrumbItem/BreadcrumbItem.scss
> MOON-49: Fixed min-width

- package.json
- src/components/SecondaryNav/SecondaryNav.jsx
- yarn.lock
> MOON-71: Fixed resizable secondary nav : force flexBasis to 0

- src/components/PrimaryNav/PrimaryNav.stories.jsx
https://jira.jahia.org/browse/MOON-89
Fix error 404 with an image from PrimaryNav in a story
> MOON-89: Fix error 404 with an image from PrimaryNav in a story

- src/components/Button/Button.jsx
- src/components/ListItem/ListItem.jsx
- src/components/Menu/MenuItem.jsx
> MOON-100 : Added isHtml prop on Button / ListItem / MenuItem

- src/components/PrimaryNav/PrimaryNav.scss
- src/components/PrimaryNav/PrimaryNav.stories.jsx
https://jira.jahia.org/browse/MOON-101
Update mode icon position
> MOON-101 Align mode icon to be a bit more consistent with figma

- src/components/ListItem/ListItem.jsx
https://jira.jahia.org/browse/BACKLOG-12798
pass icon props to the icon so if we are using some mandatory attribute like src, the icon will be displayed correctly
> BACKLOG-12798 pass icon props to the icon so if we are using some mandatory attribute like src, the icon will be displayed correctly

- src/data/treeDataNested.js
https://jira.jahia.org/browse/MOON-103
Add a missing `toIconComponent` to `treeDataNested`
> MOON-103: Fix error on Layout/Demo story

- src/components/SecondaryNav/SecondaryNavHeader/SecondaryNavHeader.jsx
- src/components/SecondaryNav/SecondaryNavHeader/SecondaryNavHeader.scss
https://jira.jahia.org/browse/BACKLOG-12813
Improve font size
> BACKLOG-12813 Make header font size as on figma

- src/components/Button/Button.scss
https://jira.jahia.org/browse/MOON-105
> MOON-105: Unify button height for the small variant

- src/components/Menu/Menu.scss
https://jira.jahia.org/browse/MOON-104
Fix menu overflow with Safari
> MOON-104: Fix menu overflow with Safari

- src/components/PrimaryNav/PrimaryNavItem/PrimaryNavItem.jsx
https://jira.jahia.org/browse/MOON-110
Add title attribute on PrimaryNavItem to help understanding when the navigation Lvl 1 is collapsed
> MOON-110: Add title attribute on PrimaryNavItem

- src/components/Accordion/AccordionItem/AccordionItem.scss
- src/components/ListItem/ListItem.stories.jsx
- src/components/Menu/MenuItem.scss
- src/components/TabItem/variants/_ghost.scss
- src/components/Typography/Typography.scss
- src/globals/_init.scss
- src/tokens/colors/_colors.scss
- src/tokens/colors/color.stories.jsx
- src/tokens/colors/colors.stories.scss
https://jira.jahia.org/browse/MOON-106
**Accordion**
Remove hover styling on selected AccordionItem
**ListItem**
Update storybook to fit the component behavior
**MenuItem**
Increase horizontal spacing
**TabItem**
Remove "jump" when TabItem is selected
**PrimaryNavItem**
Add background on hover
**Colors**
Storybook presents all colors
**Typography**
Manage semiBold weight (Chip component was too bold)
> MOON-106: Design improvements

- src/components/Accordion/AccordionItem/AccordionItem.scss
- src/components/Button/variants/_default.scss
- src/components/Button/variants/_ghost.scss
- src/components/PrimaryNav/PrimaryNav.jsx
- src/components/PrimaryNav/PrimaryNav.scss
- src/components/PrimaryNav/PrimaryNav.stories.jsx
- src/components/PrimaryNav/PrimaryNavItem/PrimaryNavItem.scss
- src/components/PrimaryNav/PrimaryNavItem/PrimaryNavItem.stories.jsx
- src/components/TabItem/variants/_ghost.scss
https://jira.jahia.org/browse/MOON-112
**PrimaryNav**
- Add background on hover of the burger menu and the back icon arrow
**PrimaryNavItem**
- Add background on hover
**Accordion**
- Remove the border-bottom of the last AccordionItem
- Increase the height of AccordionHeader to fit the design
**Button/TabItem**
- Remove border for some variants/states
> MOON-112: Design improvements

- src/components/Button/Button.jsx
https://jira.jahia.org/browse/MOON-111
Remove focus after clicking on a button
> MOON-111: Remove focus after clicking on a button

- src/components/TreeView/ControlledTreeView.jsx
- src/components/TreeView/TreeView.scss
- src/components/TreeView/TreeView.stories.jsx
- src/data/treeData.js
- src/layouts/Layouts.stories.jsx
https://jira.jahia.org/browse/MOON-114
- Manage flat treeView
- Manage shift when a node has an icon and its children don't have one
> MOON-114: Improve TreeView shift

- src/components/Chip/Chip.jsx
- src/components/Chip/Chip.scss
- src/tokens/colors/_colors.scss
- src/tokens/colors/color.stories.jsx
- src/tokens/colors/colors.stories.scss
https://jira.jahia.org/browse/MOON-120
- Add new color `purple`
- Add new Chip variant `reassuring` 
> Moon 120: New Chip variant

- src/components/Button/Button.scss
https://jira.jahia.org/browse/MOON-119
Set the height to the Button component
> MOON-119: Set a height to Button

- src/components/Accordion/AccordionItem/AccordionItem.scss
https://jira.jahia.org/browse/MOON-118
Update accordion colors/background/border
> Moon 118: Update Accordion styling

- src/components/Separator/Separator.jsx
- src/components/Separator/Separator.scss
https://jira.jahia.org/browse/MOON-121
Add the spacing option 'none' to the Separator component
> MOON-121: Add the spacing option 'none' to the Separator component

- src/components/PrimaryNav/PrimaryNav.jsx
- src/components/PrimaryNav/PrimaryNav.stories.jsx
- src/components/PrimaryNav/PrimaryNavItem/PrimaryNavItem.jsx
https://jira.jahia.org/browse/BACKLOG-13003
Collapse primary nav when an item is clicked
> BACKLOG-13003 Collapse primary nav when an item is clicked

- src/components/TreeView/ControlledTreeView.jsx
- src/components/TreeView/TreeView.jsx
- src/components/TreeView/UncontrolledTreeView.jsx
https://jira.jahia.org/browse/MOON-123
add the possibility to add custom properties/attributes to tree items
> MOON-123 add the possibility to add custom properties/attributes to tree items

- src/tokens/icons/asset/Section.svg
- src/tokens/icons/asset/index.js
https://jira.jahia.org/browse/MOON-130
- Add Section icon
> MOON-130: Add Section icon

- src/components/Button/Button.scss
- src/components/Chip/Chip.scss
- src/components/TreeView/ControlledTreeView.jsx
- src/components/TreeView/TreeView.scss
- src/components/Typography/Typography.scss
https://jira.jahia.org/browse/MOON-127
- Button: Fix vertical alignment with a small variant
- Chip: Fix the height when it contains only an icon
- TreeView: Improve the shift (again)
- Typography: Just capitalize the first letter of the title variant
> Moon 127: Design improvements

- src/components/TreeView/ControlledTreeView.jsx
https://jira.jahia.org/browse/MOON-132
Fix tree alignment between siblings elements with children with icon or not
> MOON-132: Fix TreeView alignement

- README.md
https://jira.jahia.org/browse/MOON-148
Remove the link to zeroHeight in the `README.md` file.
> MOON-148: Remove the link to zeroHeight

- .storybook/webpack.config.js
https://jira.jahia.org/browse/MOON-53
> MOON-53: Fix for scss not loading properly in storybook build

- src/components/Dropdown/Dropdown.jsx
- src/components/ListItem/ListItem.jsx
- src/components/TabItem/TabItem.scss
- src/components/TabItem/variants/_ghost.scss
https://jira.jahia.org/browse/MOON-150
* Changed Dropdown label, MenuItem text, and ListItem text to use Typography variant caption as per designs
* Increased spacing between the bottom border and TabItem for selected TabItem state
> MOON-150: Increased spacing for TabItem; caption Typography variant for Dropdown/MenuItem/ListItem

- .github/workflows/lint-test.yml
- .storybook/webpack.config.js
- src/components/Dropdown/Dropdown.jsx
- src/components/ListItem/ListItem.jsx
- src/components/TabItem/TabItem.scss
- src/components/TabItem/variants/_ghost.scss
For the release of version 0.16.2.
> Release 0.16.2

- src/components/Button/Button.scss
Changing the display from flex to inline-flex to be able to have multiple buttons inline
> Changed button style to inline-flex

- src/components/Input/Input.scss
- src/components/Input/Input.spec.js
- src/components/Input/Input.stories.jsx
- src/components/Input/Input.tsx
https://jira.jahia.org/browse/MOON-135
* Design updates for the Input component
* Cancel icon only appears if `onClear` prop is passed in AND the input is filled
> MOON-135: Design updates to Input component

- src/components/ListItem/ListItem.tsx
https://jira.jahia.org/browse/MOON-157
Migrates ListItem component to typescript.
> MOON-157: Migrates ListItem component to typescript

- .github/workflows/lint-test.yml
https://jira.jahia.org/browse/MOON-199
Update GitHub workflow to lint typescript files before each PRs to the develop branch
> MOON-199: Run typescript lint script for PRs

- src/components/Dropdown/Dropdown.scss
- src/components/Dropdown/Dropdown.stories.jsx
- src/components/Dropdown/Dropdown.tsx
https://jira.jahia.org/browse/MOON-161
Adds styling for new Dropdown variant, `outlined`.
> MOON-161: Styling for outlined Dropdown variant

- src/components/Dropdown/Dropdown.md
- src/components/Dropdown/Dropdown.tsx
- src/components/Menu/Menu.tsx
https://jira.jahia.org/browse/MOON-201
* Errors occurred when searching within Dropdown Menus that had grouped options
* Added a function within Menu component to aggregate searchable children
> MOON-201: Fixes issue with searching when Dropdown Menu has groups

- src/__storybook__/IconWrapper.jsx
- src/components/Dropdown/Dropdown.md
- src/components/Dropdown/Dropdown.scss
- src/components/Dropdown/Dropdown.stories.jsx
- src/components/Dropdown/Dropdown.tsx
- src/components/Menu/Menu.spec.js
- src/components/Menu/Menu.tsx
- src/components/Menu/MenuItem.tsx
- src/components/Typography/Typography.stories.jsx
https://jira.jahia.org/browse/MOON-170
* New `outlined` Dropdown variant changes after Design review
* Fixes a bug where the selected Dropdown option was not highlighted in menu
* Adds Playground story for Dropdown
* Moves Typography stories to the "Tokens" section of storybook
> MOON-170: Outlined Dropdown Changes After Design Review

- .circleci/config.yml
- src/components/Badge/Badge.stories.jsx
- src/components/Badge/Badge.tsx
- src/components/Dropdown/Dropdown.stories.jsx
- src/components/Dropdown/Dropdown.tsx
- src/components/Input/Input.stories.jsx
- src/components/Input/Input.tsx
- src/components/ListItem/ListItem.tsx
- src/components/Menu/Menu.tsx
- src/components/Menu/MenuItem.tsx
- src/components/Separator/Separator.stories.jsx
- src/components/Separator/Separator.tsx
- src/components/Typography/Typography.tsx
https://jira.jahia.org/browse/MOON-212
* Updates CircleCI config so that Github is added to known hosts
* Cleans up typescript naming convention
> MOON-212: Small updates to CircleCI config and typescript naming convention

- src/components/Dropdown/Dropdown.tsx
https://jira.jahia.org/browse/MOON-216
Increased the minimum width of the dropdown menu to 80px as 70px was not enough.
> MOON-216: Increase minimum width for dropdown menu to 80px

- .github/workflows/deploy-storybook.yml
https://jira.jahia.org/browse/MOON-229
* Reverting back some of the changes to the deploy storybook github actions workflow as the new version did not deploy properly on release
> MOON-229: Revert back some changes to Github pages deployment

- src/components/ButtonGroup/ButtonGroup.tsx
- src/components/ButtonGroup/ButtonGroup.types.ts
https://jira.jahia.org/browse/TECH-337
> TECH-337: Convert ButtonGroup component to typescript

- src/components/Accordion/Accordion.jsx
- src/components/Accordion/Accordion.spec.js
- src/components/Badge/Badge.spec.js
- src/components/Badge/Badge.tsx
- src/components/Breadcrumb/Breadcrumb.jsx
- src/components/Breadcrumb/Breadcrumb.spec.js
- src/components/ButtonGroup/ButtonGroup.spec.js
- src/components/ButtonGroup/ButtonGroup.tsx
- src/components/Menu/Menu.spec.js
- src/components/Menu/Menu.tsx
- src/components/Tab/Tab.jsx
- src/components/Tab/Tab.spec.js
- src/components/TreeView/TreeView.jsx
- src/components/TreeView/TreeView.spec.js
- src/components/Typography/Typography.spec.js
- src/components/Typography/Typography.tsx
https://jira.jahia.org/browse/MOON-220
Avoid rendering something when the component is empty and have no children/items.
> MOON-220: Avoid to render something when the component is empty

- .storybook/main.js
- package.json
- src/components/Loader/Loader.scss
- src/components/Loader/Loader.spec.js
- src/components/Loader/Loader.stories.tsx
- src/components/Loader/Loader.tsx
- src/components/Loader/Loader.types.ts
- src/components/Loader/index.ts
- src/components/index.ts
- yarn.lock
https://jira.jahia.org/browse/MOON-264
- Create a loader component with 3 different sizes
- Add  `@storybook/addon-controls`
> MOON-264: Create the Loader components

- .storybook/main.js
- src/components/Header/Header.scss
- src/components/Header/Header.spec.js
- src/components/Header/Header.stories.jsx
- src/components/Header/Header.tsx
- src/components/Header/Header.types.ts
- src/components/Header/index.ts
- src/components/Loader/Loader.stories.tsx
- src/components/index.ts
https://jira.jahia.org/browse/MOON-256
- Create the Header component
> MOON-256: Create the Header component

- package.json
- src/components/Checkbox/Checkbox.scss
- src/components/Checkbox/Checkbox.spec.js
- src/components/Checkbox/Checkbox.stories.tsx
- src/components/Checkbox/Checkbox.tsx
- src/components/Checkbox/Checkbox.types.ts
- src/components/Checkbox/index.ts
- src/components/index.ts
- yarn.lock
https://jira.jahia.org/browse/MOON-185
A simple Checkbox component that has the ability to be checked off or in indeterminate state.
> MOON-185: Checkbox Component

- .circleci/config.yml
- src/components/Table/SortIndicator/SortIndicator.scss
- src/components/Table/SortIndicator/SortIndicator.tsx
- src/components/Table/SortIndicator/SortIndicator.types.ts
- src/components/Table/SortIndicator/index.ts
- src/components/Table/Table.stories.jsx
- src/components/Table/index.ts
- src/components/Table/table-cells/TableBodyCell.tsx
- src/components/Table/table-cells/TableCell.tsx
- src/components/Table/table-cells/TableHeadCell.tsx
- src/components/Table/table-cells/tableCell.scss
- src/components/Table/table-cells/tableCell.types.ts
- src/data/tableDataFlat.tsx
https://jira.jahia.org/browse/MOON-286
- Styling for table sorting
- Created `SortIndicator` component
- Some refactoring of flat table data object and `TableBodyCell` and `TableHeadCell` to be more simple
> MOON-286: WIP Table - Set up table sorting styling and example story

- src/components/IconTextIcon/IconTextIcon.scss
- src/components/IconTextIcon/IconTextIcon.tsx
- src/components/Table/Table.stories.jsx
- src/components/Table/table-cells/TableBodyCell.tsx
- src/components/Table/table-cells/TableCell.types.ts
https://jira.jahia.org/browse/MOON-297
- Create a flat data story and a nested data story to show Table component with all features included
- Some cleanup to Table components (fixes some layout bugs)
> MOON-297: Create "kitchen sink" story examples with all Table component features

- src/components/Tab/TabItem/TabItem.scss
- src/components/Tab/TabItem/TabItem.stories.jsx
- src/components/Tab/TabItem/TabItem.tsx
- src/components/Tab/TabItem/variants/_ghost.scss
https://jira.jahia.org/browse/MOON-214
- Updated the big Tab component size to correspond with the Figma design for the jContent table's structured view
> MOON-214: Big Tab Size

- src/components/Header/Header.scss
https://jira.jahia.org/browse/MOON-307
Add a white background to the Header component
> MOON-307: Add a background-color to the Header component

- src/components/Table/TablePagination/TablePagination.spec.js
- src/components/Table/TablePagination/TablePagination.tsx
https://jira.jahia.org/browse/BACKLOG-16279
- Added data-sel-roles to some of the table pagination elements
- Added unit tests
> BACKLOG-16279: Add data-sel-role tags to table pagination component

- .husky/pre-commit
- .husky/pre-push
- package.json
- src/components/Table/Table.scss
- src/components/Table/Table.stories.jsx
- src/components/Table/Table.tsx
- src/components/Table/TableBody/TableBody.scss
- src/components/Table/TableBody/TableBody.tsx
- src/components/Table/TableRow/TableRow.scss
- src/components/Table/TableRow/TableRow.tsx
- src/components/Table/table-cells/TableBodyCell.tsx
- src/components/Table/table-cells/TableCell.scss
- src/components/Table/table-cells/TableCell.types.ts
- src/components/Table/table-cells/TableHeadCell.tsx
- src/components/Typography/Typography.types.ts
- yarn.lock
https://jira.jahia.org/browse/MOON-299
- The table layout is managed with an old-good CSS flexbox, so we can't use `useFlexbox` or other 
plugins layout from react-table.
- We have to set a width to the `TableCellBody` **and** `TableCellHeader`
- When no width is provided the cell takes all space available
- When no width is set at all, or cells are the same size
> MOON-299: Allow to add a width to each cells

- src/components/Checkbox/Checkbox.scss
- src/components/Checkbox/Checkbox.spec.js
- src/components/Checkbox/ControlledCheckbox.tsx
- src/components/Checkbox/ControlledCheckbox.types.ts
- src/components/Checkbox/UncontrolledCheckbox.tsx
- src/components/Checkbox/UncontrolledCheckbox.types.ts
https://jira.jahia.org/browse/MOON-309
Manage two checkbox sizes `default` and `big`
> MOON-309: Manage checkbox sizes

- src/components/Menu/Menu.spec.js
- src/components/Menu/MenuItem.tsx
https://jira.jahia.org/browse/MOON-313
Allow to add className to MenuItem
> MOON-313: Allow to add className to MenuItem

- .github/workflows/deploy-storybook.yml
As per the docs available here: https://github.com/peaceiris/actions-gh-pages/tree/v2#%EF%B8%8F-set-custom-commit-message
> Updated action parameters

- src/components/Table/table-cells/TableBodyCell.tsx
- src/components/Table/table-cells/TableCell.scss
- src/components/Table/table-cells/TableCell.types.ts
https://jira.jahia.org/browse/BACKLOG-16359
Allow cell to scroll when it contains overflowing content
> Backlog 16359 scroll table cells

- .github/workflows/deploy-storybook.yml
- src/components/Button/Button.scss
- src/components/Button/Button.stories.jsx
- src/components/Button/Button.tsx
- src/components/Button/Button.types.ts
- src/components/Loader/Loader.scss
- src/components/Loader/Loader.tsx
- src/components/Loader/Loader.types.ts
- src/components/Table/table-cells/TableBodyCell.tsx
- src/components/Table/table-cells/TableCell.scss
- src/components/Table/table-cells/TableCell.types.ts
Release next moonstone version
- Update deploy-storybook.yml
- MOON-308: Add a loading state to the Button
- BACKLOG-16359: scroll table cells
> Release moonstone

- src/components/TreeView/TreeView.spec.js
- src/icons/utils/toIconComponent.tsx
https://jira.jahia.org/browse/BACKLOG-16570
> BACKLOG-16570: Fixed toIconComponent

- src/components/Input/ControlledInput.tsx
- src/components/Input/Input.spec.js
- src/components/Input/Input.stories.jsx
- src/components/Input/Input.tsx
- src/components/Input/Input.types.ts
- src/components/Input/UncontrolledInput.tsx
- src/components/Menu/Menu.spec.js
https://jira.jahia.org/browse/MOON-321
- Add Controlled/Uncontrolled Input
- Use a Button to clear the field
- Update tests and rewrite them with testing-library
> MOON-321: Add Controlled/Uncontrolled Input

- src/components/Checkbox/Checkbox.spec.js
- src/components/Checkbox/ControlledCheckbox.tsx
https://jira.jahia.org/browse/MOON-323
- Fix disabled and read-only checkbox state
- Add tests
> MOON-323: Fix disabled and read-only checkbox state

- src/components/Dropdown/Dropdown.scss
- src/components/Dropdown/Dropdown.stories.jsx
- src/components/Dropdown/Dropdown.tsx
- src/components/Dropdown/Dropdown.types.ts
- src/components/Dropdown/DropdownMenu.tsx
- src/components/Dropdown/DropdownMenu.types.tsx
- src/components/Dropdown/TreeViewMenu.tsx
- src/components/Dropdown/TreeViewMenu.types.ts
- src/components/Menu/Menu.types.ts
- src/components/TreeView/ControlledTreeView.tsx
- src/components/TreeView/TreeView.md
- src/components/TreeView/TreeView.scss
- src/components/TreeView/TreeView.types.ts
- src/data/treeData.js
https://jira.jahia.org/browse/MOON-305
This is POC - work in progress
> MOON-305: POC for treeview in dropdown

- src/components/Button/variants/_ghost.scss
- src/components/Button/variants/_outlined.scss
https://jira.jahia.org/browse/MOON-324
Prevent hover style on disabled buttons
> MOON-324: Prevent hover style on disabled buttons

- src/rulesconfig-wp.js
https://jira.jahia.org/browse/QA-14185
> QA-14185: Use asset type for external files

- src/components/Collapsible/Collapsible.scss
- src/components/Collapsible/ControlledCollapsible.tsx
- src/globals/_init.scss
https://jira.jahia.org/browse/BACKLOG-17115
- Fonts and color adjustement
> BACKLOG-17115: Styling adjustements

- src/components/Accordion/AccordionItem/AccordionItem.scss
- src/components/SecondaryNav/SecondaryNav.scss
- src/components/SecondaryNav/SecondaryNav.tsx
- src/components/SecondaryNav/SecondaryNav.types.ts
- src/layouts/Layouts.stories.jsx
- src/layouts/content/LayoutContent.scss
- src/layouts/content/LayoutContent.tsx
https://jira.jahia.org/browse/MOON-341
- Add `isReversed` to `SecondaryNav`. It's set to `true` by default to be retro compatible with what we already have.
- Minor color change to `AccordionItem` in light theme.
> MOON-341: Manage isReversed to SecondaryNav

- .autorc
- .github/workflows/on-merge.yml
- package.json
https://jira.jahia.org/browse/MOON-568
Simply the workflow and use [auto shipit](https://intuit.github.io/auto/docs/generated/shipit) to manage the release and publish to npm.
> TECH-568: Fix release workflow

- package.json
- yarn.lock
https://jira.jahia.org/browse/MOON-342
Update auto dependency
> MOON-342: Update auto dependency

- src/components/Dropdown/DropdownMenu.tsx
- src/hooks/usePositioning.tsx
https://jira.jahia.org/browse/MOON-314
> MOON-314: Use fixed position

- src/layouts/module/LayoutModule.tsx
https://jira.jahia.org/browse/MOON-346
Fix layout issue when content with a huge width is displayed in LayoutModule
> MOON-346: Fix layout issue with LayoutModule

- src/components/Header/Header.scss
https://jira.jahia.org/browse/MOON-349
Remove z-index from Header component
> MOON-349: Remove z-index from Header component

- src/components/Checkbox/Checkbox.scss
https://jira.jahia.org/browse/MOON-350
Prevent hover style on disabled/readonly checkbox
> MOON-350: Prevent hover style on disabled/readonly checkbox

- src/components/Radio/ControlledRadio.tsx
- src/components/Radio/Radio.scss
- src/components/Radio/Radio.spec.js
- src/components/Radio/Radio.stories.tsx
- src/components/Radio/Radio.tsx
- src/components/Radio/Radio.types.ts
- src/components/Radio/UncontrolledRadio.tsx
- src/components/Radio/index.ts
- src/components/Typography/Typography.types.ts
- src/components/index.ts
https://jira.jahia.org/browse/MOON-352
> MOON-352: Add radio button moonstone component

- src/globals/_dnd.scss
https://jira.jahia.org/browse/MOON-355
We should have a similar design between the drop and the re-ordering.
> MOON-355: Update styling of the re-order

- src/components/Separator/Separator.scss
https://jira.jahia.org/browse/BACKLOG-20115
> BACKLOG-20115: Hide following separators

- src/components/Dropdown/Dropdown.stories.jsx
- src/components/ListItem/ListItem.stories.tsx
- src/components/Menu/Menu.stories.tsx
https://jira.jahia.org/browse/MOON-362
Add story for Dropdown with description
> MOON-362: Add story for Dropdown with description

- .github/workflows/deploy-storybook.yml
- .github/workflows/on-code-change.yml
- .github/workflows/on-merge.yml
https://jira.jahia.org/browse/TECH-1081
Update deprecated steps
> TECH-1081 Update deprecated steps

- src/components/Dropdown/Dropdown.tsx
- src/components/Dropdown/TreeViewMenu.tsx
https://jira.jahia.org/browse/MOON-333
> MOON-333: test undefined, fixed find in tree

- src/components/Input/BaseInput/BaseInput.scss
- src/components/Input/SearchContextInput/SearchContextInput.tsx
https://jira.jahia.org/browse/MOON-333
> MOON-333: Fixed warnings

- src/components/Dropdown/Dropdown.spec.js
- src/components/Menu/Menu.tsx
https://jira.jahia.org/browse/MOON-326
> MOON-326: Add auto-add search logic for grouped data

- src/components/Dropdown/Dropdown.spec.js
- src/components/Dropdown/Dropdown.tsx
- src/components/Dropdown/Dropdown.types.ts
- src/components/Dropdown/DropdownMenu.tsx
- src/components/Dropdown/DropdownMenu.types.tsx
- src/components/Dropdown/TreeViewMenu.tsx
- src/components/Dropdown/TreeViewMenu.types.ts
- src/components/Menu/Menu.spec.js
- src/components/Menu/Menu.tsx
- src/components/Menu/Menu.types.ts
https://jira.jahia.org/browse/MOON-326
Cherry-pick from develop branch and merge to master
Associated PRs https://github.com/Jahia/moonstone/pull/361 and https://github.com/Jahia/moonstone/pull/362
> MOON-326: Add autosearch option for dropdown menus

- src/components/ListSelector/ValueList/ValueList.tsx
- src/components/ListSelector/ValueList/ValueList.types.ts
https://jira.jahia.org/browse/QA-14659
Remove item from right-list only via icon click. We still allow clicks on left-list items.
> QA-14659 Remove item from right-list only via icon click

- src/components/Input/BaseInput/BaseInput.scss
- src/components/Menu/Menu.stories.tsx
https://jira.jahia.org/browse/MOON-369
Prevent reversed style on input when it used in a Menu
> MOON-369: Prevent reversed style on input when it used in a Menu

- package.json
- src/components/ListSelector/ValueList/ValueList.scss
- yarn.lock
https://jira.jahia.org/browse/BACKLOG-20712
Trigger release of latest changes
> BACKLOG-20712 Trigger release

- src/components/PrimaryNav/PrimaryNav.scss
- src/components/PrimaryNav/PrimaryNav.tsx
https://jira.jahia.org/browse/QA-14444
> QA-14444: Show scrollbar

- src/components/Menu/MenuItem.scss
https://jira.jahia.org/browse/MOON-370
Improve the design of `MenuItem` variant `title`.
> MOON-370: Improve the design of MenuItem variant title

- src/components/Accordion/AccordionItem/AccordionItem.tsx
https://jira.jahia.org/browse/BACKLOG-20393
Add flexColumn on Accordion content to avoid breaking the whole flex structure at this level and be able to use flex down stream
> BACKLOG-20393: Add flexColumn on Accordion content.

- src/hooks/usePositioning.tsx
https://jira.jahia.org/browse/QA-14618
> QA-14618: delete left position if parent has transform property

- .github/workflows/on-merge.yml
- package.json
- yarn.lock
https://jira.jahia.org/browse/MOON-416
- Update auto dependency
- Update versions of github actions
> MOON-416: Fix release

- .github/workflows/on-merge.yml
- .gitignore
- package.json
- webpack.config.js
- yarn.lock
https://jira.jahia.org/browse/TECH-1270
Add SBOM creation
> TECH-1270: Add SBOM creation

- .github/workflows/on-code-change.yml
- .github/workflows/on-merge.yml
https://jira.jahia.org/browse/TECH-1270
Add step in the on-merge workflow to upload the created bom files after build
> TECH-1270: Add step to upload the created bom files

- .github/workflows/deploy-storybook.yml
- .github/workflows/on-code-change.yml
https://jira.jahia.org/browse/TECH-1639
Upgrade actions
> TECH-1639 Upgrade actions

- src/components/Accordion/AccordionItem/AccordionItem.tsx
…
https://jira.jahia.org/browse/QA-15250
AccordionItem issues when there is too many entries, the two columns move next to each other
> QA-15250: Fix rendering of AccordionItem content by using nowrap columns instead of wrapping ones

- src/components/Accordion/Accordion.spec.js
- src/components/Accordion/AccordionItem/AccordionItem.spec.jsx
https://jira.jahia.org/browse/MOON-259
Migration from 'component-test-utils-react' to 'testing-library' on components Accordion & AccordionItem.
> MOON-259: Migrated tests of Accordion & AccordionItem to testing-library

- src/components/RadioGroup/RadioItem/RadioItem.stories.tsx
https://jira.jahia.org/browse/MOON-388
Migrate radioItem story to Typescript
> MOON-388: Migrate RadioItem story to Typescript

- src/tokens/colors/_colors.scss
- src/tokens/colors/color.stories.jsx
- src/tokens/colors/colors.stories.scss
https://jira.jahia.org/browse/MOON-443
Add $colorName20 variant for all colors
> MOON-443: Add 20% opacity tint on all colors

- src/components/ResizableBox/ResizableBox.spec.js
https://jira.jahia.org/browse/MOON-437
Migrate tests of ResizableBox from react component-test-utils to react testing-library
> MOON-437: Migrate tests of ResizableBox

- src/components/SvgWrapper/SvgWrapper.spec.jsx
https://jira.jahia.org/browse/MOON-440
Migrate tests of SvgWrapper from react component-test-utils to react testing-library
> MOON-440: Migrate tests of SvgWrapper

- src/components/Typography/Typography.spec.js
https://jira.jahia.org/browse/MOON-442
Migrate tests of Typography from react component-test-utils to react testing-library
> MOON-442: Migrate tests of Typography

- src/components/Input/BaseInput/BaseInput.types.ts
- src/components/Input/BaseInput/ControlledBaseInput.tsx
https://jira.jahia.org/browse/MOON-422
Remove triggerButtonIcon and isShowTriggerButton
> MOON-422: Remove triggerButtonIcon and isShowTriggerButton

- src/components/Chip/Chip.scss
- src/components/Chip/Chip.stories.tsx
- src/components/Chip/Chip.tsx
- src/components/Chip/Chip.types.ts
https://jira.jahia.org/browse/MOON-458
Add new colors to Chip component
Add variants default & bright to Chip component
> MOON-458: Add new colors & variants to Chip component

- .github/workflows/on-code-change.yml
https://jira.jahia.org/browse/MOON-470
Replace `yarn install --frozen-lockfile` with `yarn install --immutable` in .github/workflows/on-code-change.yml
> MOON-470: Replace yarn install --frozen-lockfile with --immutable

- src/components/CardSelector/CardSelector.scss
- src/components/CardSelector/EmptyCardSelector/EmptyCardSelector.scss
- src/components/Dropdown/Dropdown.scss
- src/components/Input/BaseInput/BaseInput.scss
- src/components/ListSelector/ValueList/ValueList.scss
- src/globals.scss
- src/tokens/borders/_borders.scss
https://jira.jahia.org/browse/MOON-377
Add global border variables for selectors
> MOON-377: Add border variables for selectors

- src/components/Input/BaseInput/BaseInput.scss
https://jira.jahia.org/browse/MOON-463
Set `background-color: white` to BaseInput & remove input's default background
> MOON-463: Set background color to parent div of input

- src/components/CardSelector/CardSelector.scss
- src/components/CardSelector/EmptyCardSelector/EmptyCardSelector.scss
- src/components/Dropdown/Dropdown.scss
- src/components/Field/Field.stories.tsx
- src/components/Header/Header.scss
- src/components/Input/BaseInput/BaseInput.scss
- src/components/ListSelector/ValueList/ValueList.scss
- src/components/Textarea/Textarea.scss
- src/globals.scss
- src/globals/_variables.scss
- src/tokens/borders/_borders.scss
https://jira.jahia.org/browse/MOON-476
- Add new globals `--background-selector` & `--radius-selector`
- Add Textarea to Field's story
- Fixes to unify selectors' styling
> MOON-476: Unify the styling of selectors

- src/components/Dropdown/Dropdown.tsx
- src/components/Dropdown/DropdownMenu.tsx
- src/components/Dropdown/DropdownMenu.types.tsx
- src/components/Dropdown/TreeViewMenu.tsx
- src/components/Dropdown/TreeViewMenu.types.ts
- src/components/Input/BaseInput/BaseInput.types.ts
- src/components/Input/BaseInput/ControlledBaseInput.tsx
- src/components/Menu/Menu.tsx
- src/components/Menu/MenuItem.types.ts
https://jira.jahia.org/browse/MOON-462
Replace function `onKeyPress` with `onKeyUp`
> MOON-462: replace function onKeyPress with onKeyUp

- src/components/Field/FieldBoolean/FieldBoolean.tsx
- src/components/Fieldset/DynamicFieldset/ControlledDynamicFieldset.tsx
https://jira.jahia.org/browse/MOON-482
Add `htmlFor` on `FieldBoolean` & `DynamicField`'s labels so that clicking them toggles the `Switch`/`Checkbox`
> MOON-482: Add htmlFor on FieldBoolean & DynamicField's labels

- src/components/ListSelector/ListSelector.tsx
- src/components/ListSelector/ValueList/ValueList.tsx
https://jira.jahia.org/browse/QA-15352
- Add missing parameter on `onDragOver` event
- Check for falsey values in `value` instead of just undefined (it can also come back as null and throw errors)
> QA-15352: Fix dnd issue for ListSelector

- src/components/Table/Table.stories.jsx
- src/components/Table/TableRow/TableRow.scss
- Fix the contrast issue when a button is on a highlighted row
- Fix indentation in table story
- Add an example with buttons in a table
> fix: contrast issue when a button is on a highlighted row

- package.json
- src/components/Tooltip/Tooltip.scss
- src/components/Tooltip/Tooltip.spec.js
- src/components/Tooltip/Tooltip.stories.tsx
- src/components/Tooltip/Tooltip.tsx
- src/components/Tooltip/Tooltip.types.tsx
- src/components/Tooltip/index.ts
- src/components/index.ts
- yarn.lock
Add new dependency `@floating-ui/react`
Add new component `Tooltip`
> feat(component): add Tooltip with new dependency react floating UI

- src/components/CardSelector/CardSelector.scss
- src/components/CardSelector/CardSelector.spec.js
- src/components/CardSelector/CardSelector.tsx
- src/components/CardSelector/CardSelector.types.ts
- src/components/CardSelector/EmptyCardSelector/EmptyCardSelector.scss
- src/components/Fieldset/Fieldset.stories.tsx
Remove isDraggable prop
Reduce cardSelector height
Other fixes...
> feat: Improve cardSelector

- package.json
- vite.config.mjs
- yarn.lock
Produce SBOM to please the CI (and for security of course)
> build: produce sbom

- src/components/SvgWrapper/SvgWrapper.stories.tsx
Migrate SvgWrapper story to Typescript
> chore: Migrate SvgWrapper story to Typescript

- src/components/Header/Header.stories.tsx
Migrate Header stories to Typescript
> chore: Migrate Header stories to Typescript

- src/components/PrimaryNav/PrimaryNav.stories.tsx
- src/components/PrimaryNav/PrimaryNavItem/PrimaryNavItem.stories.tsx
Migrate primaryNav & primaryNavItem stories to Typescript
> chore: Migrate primaryNav & primaryNavItem stories to Typescript

- src/components/Accordion/AccordionItem/AccordionItem.tsx
- src/components/Dropdown/Dropdown.tsx
- src/components/Dropdown/DropdownMenu.tsx
- src/components/ListSelector/ValueList/ValueList.tsx
- src/components/PrimaryNav/PrimaryNavItem/PrimaryNavItem.tsx
- src/hooks/useAccessibleClick.spec.tsx
- src/hooks/useAccessibleClick.tsx
Create useAccessibleClick hook
Replace non-button element's onClick with onAccessibleClick
> feat: Create useAccessibleClick to manage accessibility with onClick function

- package.json
- vite.config.mjs
Provide esm and cjs files in moonstone build, at least to support running of jest in jcontent
> build: Create hybrid package, provide esm, cjs artifacts

- .storybook/main.ts
As storybook [deprecates](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#commonjs-with-vite-is-deprecated) CommonJS config (because of vite).
I converted the configuration to ESM.
> fix: storybook config

- src/components/TreeView/ControlledTreeView.tsx
- src/hooks/useToggleNode.spec.tsx
- src/hooks/useToggleNode.tsx
- create `useToggleNode` hook & `useToggleNode` tests
- implement `useToggleNode` hook on component `ControlledTreeView`
> feat: Create useToggleNode hook to manage opening / closing node

- src/components/Accordion/AccordionItem/AccordionItem.tsx
- src/components/CheckboxGroup/CheckboxItem/ControlledCheckboxItem.tsx
- src/components/Dropdown/DropdownMenu.tsx
- src/components/Dropdown/TreeViewMenu.tsx
- src/components/ListSelector/ValueList/ValueList.tsx
- src/components/Menu/Menu.tsx
- src/components/Menu/MenuItem.tsx
- src/components/PrimaryNav/PrimaryNavItem/PrimaryNavItem.tsx
- src/components/RadioGroup/RadioItem/RadioItem.tsx
- src/components/TreeView/ControlledTreeView.tsx
- src/hooks/index.ts
Add `index.ts` in hooks directory and update all hooks imports
> chore: add index file in hooks directory & update hooks imports

- src/components/CheckboxGroup/CheckboxItem/ControlledCheckboxItem.tsx
- src/components/Menu/MenuItem.tsx
- src/components/RadioGroup/RadioItem/RadioItem.tsx
- src/components/Tab/Tab.tsx
- src/components/Tab/TabItem/TabItem.spec.tsx
- src/components/Tab/TabItem/TabItem.tsx
- src/components/TreeView/ControlledTreeView.tsx
- src/hooks/onArrowNavigation.spec.tsx
- src/hooks/onArrowNavigation.tsx
- Add horizontal arrow navigation using `onArrowNavigation` hook
- Add role 'tablist' on `Tab` & 'tab' on `TabItem`
- Add attribute `aria-selected` on `TabItem`
> chore: update Tabs to meet W3C standards

- src/components/Accordion/AccordionItem/AccordionItem.tsx
- src/components/Dropdown/DropdownMenu.tsx
- src/components/ListSelector/ValueList/ValueList.tsx
- src/components/PrimaryNav/PrimaryNavItem/PrimaryNavItem.tsx
- src/components/Switch/ControlledSwitch.tsx
- src/hooks/useAccessibleClick.spec.tsx
- src/hooks/useAccessibleClick.tsx
- Update & add `onAccessibleClick` hook Switch
> chore: update Switch to meet W3C standards 

- src/components/TreeView/TreeView.scss
- src/components/TreeView/TreeView.stories.jsx
- src/data/index.js
- src/data/treeDataRootClosable.tsx
- Remove icon's spacing
- Reduce item's indent
- Add story with closeable root
> fix: fixes on treeView spacings

- src/components/Separator/Separator.scss
- Change the color separator to a lighter color to focus on the content.
> feat: change separator to a lighter color

- src/components/Header/Header.stories.tsx
- src/components/Header/Header.tsx
- src/components/Header/Header.types.ts
- Deprecate backButton prop on Header
- Remove backButton from Header stories
> chore: deprecate backButton on Header

- src/components/CardSelector/EmptyCardSelector/EmptyCardSelector.scss
- src/components/Checkbox/Checkbox.scss
- src/components/Dropdown/Dropdown.scss
- src/components/Input/BaseInput/BaseInput.scss
- src/components/Input/BaseInput/ControlledBaseInput.tsx
- src/components/RadioGroup/RadioItem/RadioItem.scss
- Remove focus style on disabled, readonly & loading components
> fix: remove focus style on disabled, readonly & loading components

- src/tokens/colors/color.stories.tsx
- Migrate Colors stories to Typescript
> chore: Migrate Colors stories to Typescript

- src/components/TreeView/TreeView.stories.tsx
chore: Migration treeview story typescript
> chore: Migration treeview story file in typescript
