Jahia/moonstone

src/components/Chip/Chip.jsx
src/components/Chip/Chip.spec.js
src/components/index.js

https://jira.jahia.org/browse/MOON-50
- Chip component now accept and render custom properties as attributes
- Chip component has been added to component's index to be exported properly

MOON-50: Allow custom attributes in Chip component

---

src/components/Chip/Chip.jsx
src/components/Chip/Chip.spec.js

Added a className property to be able to provide custom CSS classes.
https://jira.jahia.org/browse/MOON-50

MOON-50: Allow CSS customization of Chip component

---

src/components/Accordion/Accordion.context.js
src/components/Accordion/Accordion.jsx
src/components/Accordion/Accordion.spec.js
src/components/Accordion/Accordion.stories.jsx
src/components/Accordion/AccordionItem/AccordionItem.jsx
src/components/Accordion/AccordionItem/AccordionItem.scss
src/components/Accordion/AccordionItem/AccordionItem.spec.jsx
src/components/Accordion/ControlledAccordion.jsx
src/components/Accordion/UncontrolledAccordion.jsx

https://jira.jahia.org/browse/MOON-58
- Authorize the opening/closing of accordion by programmation
- UI update
⚠️ The props `openByDefault ` has been renamed `defaultOpenedItem`

Moon 58: Improve accordion - makes it controllable

---

src/components/Accordion/AccordionItem/AccordionItem.jsx
src/components/Chip/Chip.jsx
src/components/PrimaryNav/PrimaryNavItem/PrimaryNavItem.jsx
src/components/PrimaryNav/PrimaryNavItem/PrimaryNavItem.scss
src/components/TreeView/ControlledTreeView.jsx
src/components/Typography/Typography.jsx
src/components/Typography/Typography.scss
src/components/Typography/Typography.spec.js
src/components/Typography/Typography.stories.jsx

https://jira.jahia.org/browse/MOON-48
Updated API of Typography component according to https://www.figma.com/file/Hn0L5ZR1taHnTIqs3Vq61q/moonstone-tokens?node-id=467%3A0
- Supported variant are now: 'title', 'heading', 'subheading', 'body' (default), 'caption', 'button'
- Added a weight property to specify font weight
- Added a isItalic property to indicate that text should be displayed in italic
- Added a isUpperCase to indicate that text should be displayed in upper case
- Added a hasLineThrough property to indicate that text should be displayed with a line- through

MOON-48: Update API of Typography component

---

package.json

https://jira.jahia.org/browse/MOON-40
As we deploy storybook with Gitgub actions to Github pages: https://jahia.github.io/moonstone
We can stop to deploy to `contenteditor.jahia.design/moonstone`

MOON-40: Remove the deploy script

---

src/components/SecondaryNav/SecondaryNav.jsx
src/components/TreeView/ControlledTreeView.jsx
src/components/TreeView/TreeView.scss
src/components/TreeView/TreeView.stories.jsx
src/data/index.js
src/data/treeData.js
src/data/treeDataNested.js
src/layouts/Layouts.stories.jsx

https://jira.jahia.org/browse/MOON-71
- Set the minimum width of the SecondaryNav to 245px (as the default size)
- Increase the maximum width of the SecondaryNav to 900px
- Avoid icon's tree to overlaps with small SecondaryNav
- Add a complete story example of the SecondaryNav in `Layout/Demos`

Moon 71: Update min/max width of SecondaryNav expanded

---

.stylelintrc.json
src/components/Separator/Separator.scss
src/components/Separator/Separator.stories.jsx
src/layouts/app/LayoutApp.stories.jsx
src/layouts/module/LayoutModule.stories.jsx
src/utils/_helpers.scss

https://jira.jahia.org/browse/QA-12658
- Remove height based on 100%
- Add a stylelint rule to forbid using percentage unit with a height

QA-12658: Remove height:100% to the vertical separator

---

src/layouts/module/LayoutModule.jsx
src/layouts/module/LayoutModule.spec.jsx

https://jira.jahia.org/browse/MOON-95
Add a `component` props to the `LayoutModule` to choose the render HTML  to avoid rendering several `main` HTML elements when we nest layout.

MOON-95: Add component props to LayoutModule

---

src/components/ButtonGroup/ButtonGroup.scss
src/components/ButtonGroup/ButtonGroup.stories.jsx

https://jira.jahia.org/browse/MOON-96
Fix displaying one button inside a ButtonGroup

MOON-96: Fix displaying one button inside a ButtonGroup

---

src/components/Separator/Separator.jsx
src/components/Separator/Separator.scss
src/components/Separator/Separator.spec.js
src/components/Separator/Separator.stories.jsx

https://jira.jahia.org/browse/BACKLOG-12710
add property invisible to the Separator so that we can hide it it is the first-child, last-child or only-child

BACKLOG-12710 add property invisible to the Separator so that we can hide it it is the first-child, last-child or only-child

---

src/components/Separator/Separator.jsx
src/components/Separator/Separator.scss
src/components/Separator/Separator.spec.js

https://jira.jahia.org/browse/BACKLOG-12710
add fourth option to hide the separator if it's the first OR last child

BACKLOG-12710 add fourth option to hide the separator if it's the first OR last child

---

src/components/Dropdown/Dropdown.jsx

https://jira.jahia.org/browse/BACKLOG-12798
pass icon props to the icons so if we are using some mandatory attribute like src, the icon will be displayed correctly

BACKLOG-12798 pass icon props to the icons so if we are using some mandatory attribute like src, the icon will be displayed correctly

---

src/components/Breadcrumb/Breadcrumb.jsx

https://jira.jahia.org/browse/MOON-113
Don't' use the BreadcrumbItem's label to generate the value of the key

MOON-113: Fix the key of Breadcrumb

---

src/components/TreeView/ControlledTreeView.jsx
src/components/TreeView/TreeView.spec.js

https://jira.jahia.org/browse/MOON-98
Allow expanding a tree node by clicking on the label when no `onClickItem` isn't provided

MOON-98: Allow expanding a tree node by clicking on the label

---

src/components/Tab/Tab.jsx
src/components/Tab/Tab.scss
src/components/Tab/Tab.spec.js

https://jira.jahia.org/browse/BACKLOG-12940
Add the possibility to extend tab cmp and fix his padding

BACKLOG-12940: Add the possibility to extend tab cmp and fix his padding

---

src/components/ButtonGroup/ButtonGroup.scss

https://jira.jahia.org/browse/MOON-96
Fix styling issue on hovering a ButtonGroup with a default variant and an accent color (a double border was displayed).

MOON-96: Fix styling issue on ButtonGroup hover

---

src/components/TreeView/ControlledTreeView.jsx
src/components/TreeView/TreeView.jsx

https://jira.jahia.org/browse/MOON-131
Updated the TreeView component so that the onClickItem function prop has access to toggleNode in its parameters.

MOON-131: Add toggleNode to TreeView onClickItem

---

src/components/PrimaryNav/PrimaryNav.scss

https://jira.jahia.org/browse/BACKLOG-12731
Style changes to PrimaryNav to fix the issue where the logo was overlapping with the collapsed navbar in Safari - flexbox was behaving differently in Safari vs Chrome and Firefox.

BACKLOG-12731: Fix for logo appearing in collapsed PrimaryNav bar in Safari

---

src/components/Button/Button.scss
src/components/TabItem/TabItem.scss

https://jira.jahia.org/browse/BACKLOG-14310
Buttons and Tab Items were not inheriting the font-family as per the css reset so I specifically added `font-family: inherit` to their scss files. It also fixed the issue for the ButtonGroup and Breadcrumb components.

BACKLOG-14310: Fixes font bug for Button, ButtonGroup, Breadcrumb, TabItem

---

scripts/compile-sass.js
scripts/compile.js

https://jira.jahia.org/browse/MOON-53
Adds more files exclusions to js and scss compilations so that unnecessary files are not copied over to the build.

MOON-53: Excludes unnecessary files from build

---

src/components/Menu/Menu.scss
src/components/Menu/Menu.stories.jsx
src/components/Menu/Menu.tsx

https://jira.jahia.org/browse/MOON-169
* Adds new Menu variants: `smallImages` and `bigImages` which control the width and height of the Menu

MOON-169: Adds Menu Variants for Small and Big Images

---

src/components/Dropdown/Dropdown.md
src/components/Dropdown/Dropdown.scss
src/components/Dropdown/Dropdown.stories.jsx
src/components/Dropdown/Dropdown.tsx
src/components/Menu/Menu.scss
src/components/Menu/Menu.stories.jsx
src/components/Menu/Menu.tsx

https://jira.jahia.org/browse/MOON-160
* Adds the ability to have image dropdown options
* Assigns  the appropriate`maxWidth` and `maxHeight` to the Dropdown Menu when the `imageSize` prop is passed into the Dropdown
* Simplifies the Menu component so that it doesn't need its own `imageSize` property. It's now managed on the MenuItem/LisItem level and the Dropdown level
* Complete styling to come in the next PR

MOON-160: Adds ability to have image dropdown options

---

.github/workflows/deploy-storybook.yml

* Adds NODE_OPTIONS setting to storybook build during workflow to deploy storybook to github pages
* Once storybook has been updated to the latest version, hopefully, this will not be necessary with the newer typescript optimizations

Adds NODE_OPTIONS to Storybook Build Command

---

package.json
src/components/Dropdown/Dropdown.tsx
src/components/Menu/Menu.tsx

https://jira.jahia.org/browse/MOON-216
* The `Menu` opened by `Dropdown` will have a width which is no smaller than 70px
* Removed the node options to increase memory for node as they're no longer necessary with the storybook 6 update

MOON-216: Fixes menu truncation issue in Firefox and Safari

---

.circleci/config.yml
.github/workflows/deploy-storybook.yml

https://jira.jahia.org/browse/MOON-218
Added a custom commit message with `[skip ci]` for the commit generated by the storybook deployment github action so that CircleCI isn't triggers on the `gh-pages` branch.

MOON-218: Skip CI for gh-pages branch

---

webpack.config.js

https://jira.jahia.org/browse/MOON-216
Added webpack output.publicPath to fix errors in moonstone-alpha tests.

MOON-216: Adds webpack publicPath to fix test issues

---

src/components/Dropdown/Dropdown.spec.js
src/components/Dropdown/Dropdown.stories.jsx
src/components/Dropdown/Dropdown.tsx

https://jira.jahia.org/browse/MOON-219
Don't display the dropdown component when no array or an empty array is used as data.

MOON-219: Fix error when an empty array is used as data on dropdown

---

babel.build.config.js
package.json
yarn.lock

Add usage of babel-helper-runtime to reduce file size, especially on icons which were getting huge (more than half of the size of each js file was due to babel helpers)
Result of `wc dist/**/*.js` :
Before :  
`    9961   84312  728940 total`
After :    
`    9015   47904  481670 total`

Add babel-helpers

---

src/components/Dropdown/Dropdown.spec.js
src/components/Dropdown/Dropdown.stories.jsx
src/components/Dropdown/Dropdown.tsx

https://jira.jahia.org/browse/MOON-228
- Allow displaying dropdown with an empty array
- Set dropdown as disabled if `data` is empty and `isDisabled` isn't set
- Remove default value for `isDisabled`

MOON-228: Allow displaying dropdown with an empty array

---

README.md
src/components/Dropdown/Dropdown.scss
src/components/Dropdown/Dropdown.tsx
src/components/Menu/Menu.md
src/components/Menu/Menu.scss
src/components/Menu/Menu.stories.jsx
src/components/Menu/Menu.tsx
src/hooks/usePositioning.tsx

https://jira.jahia.org/browse/MOON-223
* Adds the prop `position` to the Menu which can be `absolute` or `fixed` (it's `fixed by default). This fixes the issue where Dropdown Menus were incorrectly placed in modals as it allows the Menu to be, optionally, absolutely positioned against a relative ancestor and, therefore, not affected by ancestors that may have transform, filter, or perspective properties.
* When `position="absolute"` is passed into the Menu component, `anchorEl` is ignored.
* Modifies the `usePositioning` custom hook to support the new prop
* Updates the Dropdown component to have `position: relative` and to specify `position="absolute"` to the Menu component within it

MOON-223: Fix Dropdown Menu positioning in modals

---

src/components/Badge/Badge.scss
src/components/Badge/Badge.spec.js
src/components/Badge/Badge.stories.jsx
src/components/Badge/Badge.tsx
src/components/Badge/Badge.types.ts

https://jira.jahia.org/browse/MOON-266
- Remove the unused `diamond` variant for the Badge component
- Add all variants in storybook
- Update the component to follow our new typescript convention
- Rewrite the tests with testing-library

MOON-266: Remove the diamond variant for the Badge component

---

src/components/Loader/Loader.tsx
src/layouts/module/LayoutModule.spec.jsx
src/layouts/module/LayoutModule.stories.jsx
src/layouts/module/LayoutModule.tsx
src/layouts/module/LayoutModule.types.ts

https://jira.jahia.org/browse/MOON-268
- Add a new prop `isLoading` to LayoutModule: replace the content by a loader
- Add a story for LayoutModule with `isLoading`
- Add the attribute `role="status"` to the Loader component for accessibility purpose
- Rewrite LayoutModule tests with testing-library

MOON-268: Add a loading state to LayoutModule

---

src/layouts/app/LayoutApp.spec.jsx
src/layouts/app/LayoutApp.stories.jsx
src/layouts/app/LayoutApp.tsx
src/layouts/app/LayoutApp.types.ts

https://jira.jahia.org/browse/MOON-271
- Add a new prop `isLoading` to LayoutApp: replace the content by a loader
- Add a story for LayoutApp with isLoading
- Rewrite LayoutApp tests with testing-library

MOON-271: Add a loading state to LayoutApp

---

src/components/Dropdown/Dropdown.stories.jsx
src/components/Dropdown/Dropdown.tsx
src/components/Dropdown/Dropdown.types.ts
src/components/ListItem/ListItem.tsx

https://jira.jahia.org/browse/MOON-272
* Fixes the down arrow icon in the Dropdown to be correctly aligned when a label isn't provided
* Update Dropdown to use our newer typescript conventions
* Changed the class on `iconEnd` on ListItem to have the correct class

MOON-272: Fix Dropdown Arrow Alignment

---

src/layouts/module/LayoutModule.tsx

https://jira.jahia.org/browse/MOON-273
Fixes a small bug that was causing a warning when using the LayoutModule component

MOON-273: Fix LayoutModule role-busy error

---

src/components/Breadcrumb/BreadcrumbItem/BreadcrumbItem.types.ts
src/components/Button/Button.tsx
src/components/Button/Button.types.ts
src/components/Tab/TabItem/TabItem.tsx
src/components/Tab/TabItem/TabItem.types.ts

https://jira.jahia.org/browse/MOON-280
Make `onClick` handler props optional for any components where they were a required prop.

MOON-280: Make onClick Handlers Optional

---

src/components/Table/Table.stories.jsx
src/components/Table/TableRow/TableRow.tsx

https://jira.jahia.org/browse/MOON-196
- Shows an example of how to specify column widths of the `Table` by using the `useFlexLayout` react-table plugin.
- See the story, "Column Width Management with React-Table" in Storybook.

MOON-196: useFlexLayout react-table plugin example

---

src/components/Menu/Menu.tsx

https://jira.jahia.org/browse/QA-13381
Basically equating right click on the overlay with a click. In jcontent a user can right click on entries in the table, if a menu is open a right click on the overlay doesn't change selection, although for the user it seems like a different entry is selected. Alternatively, we can disable right click but I think it may leave the user confused.

QA-13381 Close menu when onContextMenu is triggered on overlay

---

src/components/Table/Table.scss
src/components/Table/Table.stories.jsx
src/components/Table/Table.tsx
src/components/Table/Table.types.ts
src/components/Table/TableBody/TableBody.tsx
src/components/Table/TableBody/TableBody.types.ts
src/components/Table/TableHead/TableHead.scss
src/components/Table/TableHead/TableHead.tsx
src/components/Table/TableHead/TableHead.types.ts
src/components/Table/TableRow/TableRow.scss
src/components/Table/TableRow/TableRow.tsx
src/components/Table/TableRow/TableRow.types.ts
src/components/Table/table-cells/TableBodyCell.tsx
src/components/Table/table-cells/TableCell.scss
src/components/Table/table-cells/TableHeadCell.tsx

https://jira.jahia.org/browse/MOON-301
- Allows the header of a table to be sticky with the use of the `isSticky` prop
- Use of the sticky header causes issues with the `useFlexLayout` plugin, so its usages in `Table.stories.jsx` have been commented out for now. Further investigation into adding the ability to specify column widths will be done with MOON-299

MOON-301: Table Sticky Header

---

src/components/Menu/Menu.tsx

https://jira.jahia.org/browse/TECH-529
Do not set state to children, which is different every time, to avoid triggering a second rendering of the component.

TECH-529: Improved menu performances

---

src/components/Header/Header.stories.jsx
src/components/Header/Header.tsx

https://jira.jahia.org/browse/MOON-335
- Avoid to use `React.cloneElement` to display backButton in the header component to prevent issue with the action. Otherwise we have to set the variant `outlined`  and the icon `ArrowLeft` in the implementation side, it's no longer provided by moonstone.
- Only display header `Separator` when the `toolbar` is displayed to avoid having unnecessary element in the DOM.

MOON-335: Don't use react clone to display the backButton in the Header

---

src/layouts/content/LayoutContent.scss
src/layouts/content/LayoutContent.spec.js
src/layouts/content/LayoutContent.stories.js
src/layouts/content/LayoutContent.tsx
src/layouts/content/LayoutContent.types.ts

https://jira.jahia.org/browse/MOON-343
Add a new prop `hasPadding` to `LayoutContent` to define if the component has padding or not, by default the value is `true`.

MOON-343: Add hasPadding prop to LayoutContent

---

src/components/TreeView/ControlledTreeView.tsx
src/components/TreeView/TreeView.scss
src/components/TreeView/TreeView.stories.jsx
src/globals.scss
src/globals/_dnd.scss

https://jira.jahia.org/browse/MOON-354
- Expose some CSS classes to provide design for drag-and-drop behaviors `globals/dnd.scss`
- Move all CSS properties relative to the TreeItem at the top level of the component (`li`) instead of `div` with the class `moonstone-treeView_item`
- Rename treeItem's CSS properties for readability
- Expose new CSS properties for treeItem:
- `var(--treeItem-depth)` represents the depth level of the treeItem
- `var(--treeItem-indent)` represents the value of the shift indentation of the treeItem

MOON-354: Add global styles to provide design for drag-and-drop behaviors

---

src/components/Dropdown/Dropdown.spec.js
src/components/Dropdown/Dropdown.tsx
src/components/Dropdown/Dropdown.types.ts
src/components/Dropdown/DropdownMenu.tsx
src/components/Dropdown/DropdownMenu.types.tsx
src/components/Dropdown/TreeViewMenu.tsx
src/components/Dropdown/TreeViewMenu.types.ts
src/components/Menu/Menu.spec.js
src/components/Menu/Menu.tsx
src/components/Menu/Menu.types.ts

https://jira.jahia.org/browse/MOON-326
Add logic to be able to auto-add search input when `hasSearch=undefined`, and be able to specify limit when auto-add search input is triggered

MOON-326: Add auto-add search input for menus

---

src/components/Button/Button.scss
src/components/Button/Button.spec.js
src/components/Button/Button.stories.tsx
src/components/Button/Button.tsx
src/components/Button/Button.types.ts

https://jira.jahia.org/browse/MOON-371
- Add `iconEnd` to the Button component to allow icons at the right of the label. This new icon is only displayed when a label is provided.
- Write tests' button with testing-library

MOON-371: Add iconEnd to Button component

---

src/components/Button/Button.scss
src/components/Button/Button.spec.js
src/components/Button/Button.tsx

https://jira.jahia.org/browse/MOON-408
- When the button `isLoading`  with an icon the `Loader` is displayed instead of the icon
- When the button doesn't have an icon provided the `Loader` is displayed as overlay. The label is hidden. (same as we currently have)
- When the button `isLoading` the button is disabled to prevent `:hover`, `:active`, `:focus` style and click event
- Add tests to fit the new behavior

MOON-408: Improve button loading state

---

src/components/ListItem/ListItem.scss
src/components/ListItem/ListItem.spec.js
src/components/ListItem/ListItem.tsx
src/components/ListItem/ListItem.types.ts

https://jira.jahia.org/browse/BACKLOG-22393
- Remove fixed categorical sizes and let image size dictate the height of the row and width of image, up to a max width/height.
- Fixed `.moonstone-listItem-image_undefined` classes and default imageSize to small if not specified

BACKLOG-22393: Allow variable image sizes for Dropdown

---

src/components/TreeView/ControlledTreeView.tsx
src/components/TreeView/TreeView.spec.tsx

https://jira.jahia.org/browse/BACKLOG-21345
Ran into an issue trying to select tree item for a given tree depth using style attribute.
Add a dedicated data attribute for specifying tree item depth to simplify css attribute selection.
Related PR context: https://github.com/Jahia/jcontent/pull/1129#issuecomment-1863466587

BACKLOG-21345: Add data attribute for tree item depth

---

package.json

https://jira.jahia.org/browse/MOON-447
Fix lint:scss script error by removing single quotes on pattern in package.json

MOON-447: Fix lint:scss error on windows

---

src/components/ListItem/ListItem.scss

https://jira.jahia.org/browse/MOON-364
Replace color property with opacity property in listItem_description style

MOON-364: Fix contrast issue with dropdown description

---

src/components/Breadcrumb/Breadcrumb.spec.js
src/components/Breadcrumb/BreadcrumbItem/BreadcrumbItem.spec.js

https://jira.jahia.org/browse/MOON-432
Migrate tests of Breadcrumb and BreadcrumbItem from react component-test-utils to react testing-library

MOON-432: Migrate tests of Breadcrumb and BreadcrumbItem

---

src/components/ImgWrapper/ImgWrapper.spec.jsx

https://jira.jahia.org/browse/MOON-435
Migrate tests of ImgWrapper from react component-test-utils to react testing-library

MOON-435: Migrate tests of ImgWrapper

---

src/components/ButtonGroup/ButtonGroup.spec.js

https://jira.jahia.org/browse/MOON-433
Migrate tests of ButtonGroup from react component-test-utils to react testing-library

MOON-433: Migrate tests of ButtonGroup

---

src/components/GlobalStyle/GlobalStyle.spec.jsx

Migrate tests of GlobalStyle from react component-test-utils to react testing-library

MOON-434: Migrate tests of GlobalStyle

---

src/components/SecondaryNav/SecondaryNav.spec.js
src/components/SecondaryNav/SecondaryNav.tsx

https://jira.jahia.org/browse/MOON-438
Migrate tests of SecondaryNav from react component-test-utils to react testing-library

MOON-438: Migrate tests of SecondaryNav

---

.github/workflows/deploy-storybook.yml
.github/workflows/on-code-change.yml
.github/workflows/on-merge.yml

https://jira.jahia.org/browse/MOON-454
Update .github with more recent node version

MOON-454: Update .github with more recent node version

---

src/components/Badge/Badge.scss
src/components/Button/Button.scss
src/components/ButtonGroup/ButtonGroup.scss
src/components/CardSelector/CardSelector.scss
src/components/CardSelector/EmptyCardSelector/EmptyCardSelector.scss
src/components/Checkbox/Checkbox.scss
src/components/Dropdown/Dropdown.scss
src/components/Input/BaseInput/BaseInput.scss
src/components/ListSelector/ValueList/ValueList.scss
src/components/Menu/Menu.scss
src/components/Paper/Paper.scss
src/components/Pill/Pill.scss
src/components/PrimaryNav/PrimaryNavItem/PrimaryNavItem.scss
src/components/Tab/TabItem/TabItem.scss
src/components/Tag/Tag.scss
src/tokens/borders/_borders.scss

https://jira.jahia.org/browse/MOON-472
Add globals --selector-border-radius & --selector-border-radius_big

MOON-472: Add border radius variables for selectors

---

src/components/Dropdown/Dropdown.scss
src/components/Input/BaseInput/BaseInput.scss
src/components/Textarea/Textarea.scss
src/globals/_variables.scss

https://jira.jahia.org/browse/MOON-479
- Fix the border style on the `Dropdown` component with `ghost` variant
- Prevent `:hover` and `:focus` styling on `disabled` and `read-only` components

MOON-479: Fix border styling

---

src/components/Dropdown/Dropdown.tsx
src/components/Dropdown/DropdownMenu.tsx
src/components/Dropdown/DropdownMenu.types.tsx
src/components/Dropdown/TreeViewMenu.tsx
src/components/Dropdown/TreeViewMenu.types.ts
src/components/Input/BaseInput/BaseInput.types.ts
src/components/Input/BaseInput/ControlledBaseInput.tsx
src/components/Menu/Menu.tsx
src/components/Menu/MenuItem.types.ts

This reverts commit 43b2e42c1457105e1caad8efe95e9055d2658077.
https://jira.jahia.org/browse/MOON-462
Revert MOON-462 as it introduced a breaking change by renaming `onKeyPress`

Revert "MOON-462: replace function onKeyPress with onKeyUp (#484)"

---

.github/dependabot.yml

modify dependabot configuration to fit conventional commit

chore: modify dependabot configuration to fit conventional commit

---

src/components/TreeView/ControlledTreeView.tsx
src/components/TreeView/TreeView.spec.tsx
src/components/TreeView/TreeView.stories.jsx

Improve the loading of the tree:
- Use the `Loader` component instead of an icon with a spin animation
- The loader is now shown instead of the chevron, as it is the element clicked to trigger the opening.

feat: improve the loading of tree items

---

src/components/Tab/TabItem/TabItem.scss
src/components/Tab/TabItem/TabItem.spec.js
src/components/Tab/TabItem/TabItem.tsx

- Returns color text to gray for `TabItem`
- Prevent `:hover` style when a `TabItem` is selected
- Change weight to `semiBold` when a TabItem size is big

fix: TabItem color text returns to gray

---

src/components/ButtonGroup/ButtonGroup.scss
src/components/ButtonGroup/ButtonGroup.stories.tsx

Fix CSS classes order that can provide the wrong style when the style was not loaded in the right order.

fix: css classes order of ButtonGroup

---

src/components/Button/Button.scss
src/components/Button/Button.tsx

We must keep `Button` with `inline-flex` to make inline buttons easy to use.

fix: set Button with display inline-flex

---

src/components/Dropdown/Dropdown.scss

remove outlined dropdown's background on hover

fix: outlined dropdown background on hover

---

src/components/CardSelector/CardSelector.scss
src/components/CardSelector/CardSelector.tsx

- Prevent hover styling when the card is disabled
- Use the `disabled` attribute instead of `aria-disabled`
- Add a scss variable to set the cardSelector height

fix: cardSelector disabled style

---

src/components/CardSelector/CardSelector.scss
src/components/CardSelector/EmptyCardSelector/EmptyCardSelector.scss

- Use the same height for `CardSelector` and `EmptyCardSelector`
- Review the variable name to follow the naming convention

fix: use the same height for CardSelector and EmptyCardSelector

---

src/components/PrimaryNav/PrimaryNav.spec.tsx
src/components/PrimaryNav/PrimaryNav.tsx

- Refactor the code to use the same button for both the expand and collapse states
- Use a unique `aria-label` to describe the button
- Add the possibility to pass CSS classes to `modeIcon`
- Add a `data-testid` to the button
- Add a test about the collapse

fix: aria-label on button that toggle the PrimaryNav

---

src/components/Accordion/AccordionItem/AccordionItem.scss
src/components/ButtonToggle/ButtonToggle.scss
src/components/CardSelector/EmptyCardSelector/EmptyCardSelector.scss
src/components/Input/BaseInput/BaseInput.scss
src/components/Menu/MenuItem.scss
src/components/RadioGroup/RadioItem/RadioItem.scss
src/components/Textarea/Textarea.scss

Replace `:focus` with `:focus-visible` to only display focus style when the element is focused by keyboard and not with a simple click.

fix: Prevent focus style after clicking or selecting an item

---

src/components/TreeView/ControlledTreeView.tsx
src/components/TreeView/TreeView.spec.tsx
src/hooks/useToggleNode.spec.tsx
src/hooks/useToggleNode.tsx

- Prevent selection when clicking on the toggle icon (chevron) of the tree item
- Add `data-testid` on the toggle icon to help tests
- Add a test about this issue
- `useToggleNode` hook must not return the `onClick` function as its role is to manage the toggle state / function

fix: prevent selection on TreeView item when clicking on the chevron

---

src/components/CardSelector/CardSelector.spec.tsx
src/components/CardSelector/CardSelector.stories.tsx
src/components/CardSelector/CardSelector.tsx
src/components/CardSelector/CardSelector.types.ts

- Rename `thumbnailURL` to `thumbnail`
- Allow passing an icon component as a thumbnail
- UPdate stories
- Update the test

feat: allow icon component as thumbnail

---

src/components/CheckboxGroup/CheckboxItem/ControlledCheckboxItem.tsx
src/components/ListItem/ListItem.tsx
src/components/ListItem/ListItem.types.ts
src/components/Menu/MenuItem.tsx
src/components/RadioGroup/RadioItem/RadioItem.tsx
src/components/TreeView/ControlledTreeView.tsx
src/hooks/onArrowNavigation.spec.tsx
src/hooks/onArrowNavigation.tsx

- Add `onArrowNavigation` hook
- Add `onArrowNavigation` tests
- Implement `onArrowNavigation` list/tree/menu item type elements

feat: add onArrowNavigation to manage navigation with ArrowDown and ArrowUp

---

src/components/Breadcrumb/Breadcrumb.tsx

- Add `aria-current="page"` to last Breadcrumb item

chore: update Breadcrumbs to meet W3C standards

---

src/components/Accordion/AccordionItem/AccordionItem.scss
src/components/Breadcrumb/BreadcrumbItem/BreadcrumbItem.scss
src/components/Button/variants/_default.scss
src/components/Button/variants/_outlined.scss
src/components/CardSelector/CardSelector.scss
src/components/CardSelector/EmptyCardSelector/EmptyCardSelector.scss
src/components/Checkbox/Checkbox.scss
src/components/CheckboxGroup/CheckboxItem/CheckboxItem.scss
src/components/Collapsible/Collapsible.scss
src/components/Dropdown/Dropdown.scss
src/components/Input/BaseInput/BaseInput.scss
src/components/ListSelector/ValueList/ValueList.scss
src/components/PrimaryNav/PrimaryNavItem/PrimaryNavItem.scss
src/components/Tab/TabItem/TabItem.scss
src/components/Textarea/Textarea.scss
src/components/TreeView/TreeView.scss
src/globals/_variants.scss
src/utils/_mixins.scss

- Add `%is-focused` mixin to `/utils/_mixins.scss`
- Add `%is-focused` to unify focus style on focusable components

feat: add is-focused mixin to unify focusable components style

---

src/components/Header/Header.scss
src/components/Header/Header.stories.tsx
src/components/Header/Header.tsx

- Improve the spacing in the Header component for better balance.
- Only show a separator when `information` and `toolbar` are visible.
- Fix the flex display in `mainActions` to align the buttons on the same line.

fix: spacing in Header component

---

src/components/Dropdown/Dropdown.scss
src/components/Dropdown/Dropdown.spec.tsx
src/components/Dropdown/Dropdown.stories.jsx
src/components/Dropdown/Dropdown.tsx
src/components/Dropdown/Dropdown.types.ts
src/globals/_variants.scss

- Add prop `isLoading` to `Dropdown`

chore: add Dropdown prop isLoading

---

src/components/ListItem/ListItem.tsx
src/components/Pill/Pill.scss

- Remove `moonstone-icon_${iconSize}` from `ListItem`'s `iconStart` & `iconEnd` props as if the passed component is an `Icon` it would already have the className

fix: Fix Pill overflow in DropdownMenu
